spring:
  application:
    name: eureka-service-core

server:
  port: 8999
  servlet:
    context-path: /eureka-service-core

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

