spring:
  application:
    name: eureka-service-core

server:
  port: 8999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    # OAuth2 Client 配置，对应 OAuth2ClientProperties 类
    client:
      client-id: internal
      client-secret: internal
    # OAuth2 Resource 配置，对应 ResourceServerProperties 类
    resource:
      token-info-uri: http://uaa/oauth/check_token # 获得 Token 信息的 URL
    # 访问令牌获取 URL，自定义的

