server:
  port: 10010
spring:
  application:
    name: wcloud-gateway # 应用名
  cloud:
    gateway:
      # 路由si(集合)
      routes:
      # id唯一标识，(可自定义)
      - id: service-core
        # 路由服务地址
        uri: lb://eureka-service-core
        # 路由拦截地址(断言)
        predicates:
        - Path=/service-core/**
# Eureka服务中心配置
eureka:
  client:
    service-url:
      # 注册Eureka Server集群
      defaultZone: http://localhost:8761/eureka/